;; Generated by :claw at 2021-09-22T18:34:28.221199Z
(asdf:defsystem #:claw-linux-perf-bindings
  :description "Bindings generated by claw-linux-perf"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))
#-(:or (:and :x86-64 :linux))
(warn "Current platform unrecognized or unsupported by claw-linux-perf-bindings system")