;; Generated by :claw at 2021-09-22T18:34:28.210856Z
(uiop:define-package :%linux.perf (:use))
(uiop:define-package :claw-linux-perf-bindings~pristine (:use :cl))
(common-lisp:in-package :claw-linux-perf-bindings~pristine)

(defparameter %linux.perf::+attr-size-ver0+ 64)

(defparameter %linux.perf::+attr-size-ver1+ 72)

(defparameter %linux.perf::+attr-size-ver2+ 80)

(defparameter %linux.perf::+attr-size-ver3+ 96)

(defparameter %linux.perf::+attr-size-ver4+ 104)

(defparameter %linux.perf::+attr-size-ver5+ 112)

(defparameter %linux.perf::+attr-size-ver6+ 120)

(defparameter %linux.perf::+aux-flag-collision+ 8)

(defparameter %linux.perf::+aux-flag-overwrite+ 2)

(defparameter %linux.perf::+aux-flag-partial+ 4)

(defparameter %linux.perf::+aux-flag-truncated+ 1)

(defparameter %linux.perf::+event-ioc-disable+ 9217)

(defparameter %linux.perf::+event-ioc-enable+ 9216)

(defparameter %linux.perf::+event-ioc-id+ 2148017159)

(defparameter %linux.perf::+event-ioc-modify-attributes+ 1074275339)

(defparameter %linux.perf::+event-ioc-pause-output+ 1074013193)

(defparameter %linux.perf::+event-ioc-period+ 1074275332)

(defparameter %linux.perf::+event-ioc-query-bpf+ 3221758986)

(defparameter %linux.perf::+event-ioc-refresh+ 9218)

(defparameter %linux.perf::+event-ioc-reset+ 9219)

(defparameter %linux.perf::+event-ioc-set-bpf+ 1074013192)

(defparameter %linux.perf::+event-ioc-set-filter+ 1074275334)

(defparameter %linux.perf::+event-ioc-set-output+ 9221)

(defparameter %linux.perf::+flag-fd-cloexec+ 8)

(defparameter %linux.perf::+flag-fd-no-group+ 1)

(defparameter %linux.perf::+flag-fd-output+ 2)

(defparameter %linux.perf::+flag-pid-cgroup+ 4)

(defparameter %linux.perf::+max-contexts-per-stack+ 8)

(defparameter %linux.perf::+max-stack-depth+ 127)

(defparameter %linux.perf::+mem-blk-addr+ 4)

(defparameter %linux.perf::+mem-blk-data+ 2)

(defparameter %linux.perf::+mem-blk-na+ 1)

(defparameter %linux.perf::+mem-blk-shift+ 40)

(defparameter %linux.perf::+mem-lock-locked+ 2)

(defparameter %linux.perf::+mem-lock-na+ 1)

(defparameter %linux.perf::+mem-lock-shift+ 24)

(defparameter %linux.perf::+mem-lvlnum-any-cache+ 11)

(defparameter %linux.perf::+mem-lvlnum-l1+ 1)

(defparameter %linux.perf::+mem-lvlnum-l2+ 2)

(defparameter %linux.perf::+mem-lvlnum-l3+ 3)

(defparameter %linux.perf::+mem-lvlnum-l4+ 4)

(defparameter %linux.perf::+mem-lvlnum-lfb+ 12)

(defparameter %linux.perf::+mem-lvlnum-na+ 15)

(defparameter %linux.perf::+mem-lvlnum-pmem+ 14)

(defparameter %linux.perf::+mem-lvlnum-ram+ 13)

(defparameter %linux.perf::+mem-lvlnum-shift+ 33)

(defparameter %linux.perf::+mem-lvl-hit+ 2)

(defparameter %linux.perf::+mem-lvl-io+ 4096)

(defparameter %linux.perf::+mem-lvl-l1+ 8)

(defparameter %linux.perf::+mem-lvl-l2+ 32)

(defparameter %linux.perf::+mem-lvl-l3+ 64)

(defparameter %linux.perf::+mem-lvl-lfb+ 16)

(defparameter %linux.perf::+mem-lvl-loc-ram+ 128)

(defparameter %linux.perf::+mem-lvl-miss+ 4)

(defparameter %linux.perf::+mem-lvl-na+ 1)

(defparameter %linux.perf::+mem-lvl-rem-cce1+ 1024)

(defparameter %linux.perf::+mem-lvl-rem-cce2+ 2048)

(defparameter %linux.perf::+mem-lvl-rem-ram1+ 256)

(defparameter %linux.perf::+mem-lvl-rem-ram2+ 512)

(defparameter %linux.perf::+mem-lvl-shift+ 5)

(defparameter %linux.perf::+mem-lvl-unc+ 8192)

(defparameter %linux.perf::+mem-op-exec+ 16)

(defparameter %linux.perf::+mem-op-load+ 2)

(defparameter %linux.perf::+mem-op-na+ 1)

(defparameter %linux.perf::+mem-op-pfetch+ 8)

(defparameter %linux.perf::+mem-op-shift+ 0)

(defparameter %linux.perf::+mem-op-store+ 4)

(defparameter %linux.perf::+mem-remote-remote+ 1)

(defparameter %linux.perf::+mem-remote-shift+ 37)

(defparameter %linux.perf::+mem-snoopx-fwd+ 1)

(defparameter %linux.perf::+mem-snoopx-shift+ 38)

(defparameter %linux.perf::+mem-snoop-hit+ 4)

(defparameter %linux.perf::+mem-snoop-hitm+ 16)

(defparameter %linux.perf::+mem-snoop-miss+ 8)

(defparameter %linux.perf::+mem-snoop-na+ 1)

(defparameter %linux.perf::+mem-snoop-none+ 2)

(defparameter %linux.perf::+mem-snoop-shift+ 19)

(defparameter %linux.perf::+mem-tlb-hit+ 2)

(defparameter %linux.perf::+mem-tlb-l1+ 8)

(defparameter %linux.perf::+mem-tlb-l2+ 16)

(defparameter %linux.perf::+mem-tlb-miss+ 4)

(defparameter %linux.perf::+mem-tlb-na+ 1)

(defparameter %linux.perf::+mem-tlb-os+ 64)

(defparameter %linux.perf::+mem-tlb-shift+ 26)

(defparameter %linux.perf::+mem-tlb-wk+ 32)

(defparameter %linux.perf::+record-ksymbol-flags-unregister+ 1)

(defparameter %linux.perf::+record-misc-comm-exec+ 8192)

(defparameter %linux.perf::+record-misc-cpumode-mask+ 7)

(defparameter %linux.perf::+record-misc-cpumode-unknown+ 0)

(defparameter %linux.perf::+record-misc-exact-ip+ 16384)

(defparameter %linux.perf::+record-misc-ext-reserved+ 32768)

(defparameter %linux.perf::+record-misc-fork-exec+ 8192)

(defparameter %linux.perf::+record-misc-guest-kernel+ 4)

(defparameter %linux.perf::+record-misc-guest-user+ 5)

(defparameter %linux.perf::+record-misc-hypervisor+ 3)

(defparameter %linux.perf::+record-misc-kernel+ 1)

(defparameter %linux.perf::+record-misc-mmap-build-id+ 16384)

(defparameter %linux.perf::+record-misc-mmap-data+ 8192)

(defparameter %linux.perf::+record-misc-proc-map-parse-timeout+ 4096)

(defparameter %linux.perf::+record-misc-switch-out+ 8192)

(defparameter %linux.perf::+record-misc-switch-out-preempt+ 16384)

(defparameter %linux.perf::+record-misc-user+ 2)

(defparameter %linux.perf::+sample-branch-plm-all+ 7)

(defparameter %linux.perf::+sample-weight-type+ 16793600)

(cffi:defcenum (%linux.perf::bpf-event-type :unsigned-int)
               "/usr/include/linux/perf_event.h:1134:6"
               (:unknown 0)
               (:prog-load 1)
               (:prog-unload 2)
               (:max 3))

(cffi:defbitfield (%linux.perf::branch-sample-type :unsigned-int)
                  "/usr/include/linux/perf_event.h:194:6"
                  (:user 1)
                  (:kernel 2)
                  (:hv 4)
                  (:any 8)
                  (:any-call 16)
                  (:any-return 32)
                  (:ind-call 64)
                  (:abort-tx 128)
                  (:in-tx 256)
                  (:no-tx 512)
                  (:cond 1024)
                  (:call-stack 2048)
                  (:ind-jump 4096)
                  (:call 8192)
                  (:no-flags 16384)
                  (:no-cycles 32768)
                  (:type-save 65536)
                  (:hw-index 131072)
                  (:max 262144))

(cffi:defcenum (%linux.perf::branch-sample-type-shift :unsigned-int)
               "/usr/include/linux/perf_event.h:166:6"
               (:user-shift 0)
               (:kernel-shift 1)
               (:hv-shift 2)
               (:any-shift 3)
               (:any-call-shift 4)
               (:any-return-shift 5)
               (:ind-call-shift 6)
               (:abort-tx-shift 7)
               (:in-tx-shift 8)
               (:no-tx-shift 9)
               (:cond-shift 10)
               (:call-stack-shift 11)
               (:ind-jump-shift 12)
               (:call-shift 13)
               (:no-flags-shift 14)
               (:no-cycles-shift 15)
               (:type-save-shift 16)
               (:hw-index-shift 17)
               (:max-shift 18))

(cffi:defcenum (%linux.perf::callchain-context :unsigned-long)
               "/usr/include/linux/perf_event.h:1144:6"
               (:hv -32)
               (:kernel -128)
               (:user -512)
               (:guest -2048)
               (:guest-kernel -2176)
               (:guest-user -2560)
               (:max -4095))

(cffi:defbitfield (%linux.perf::event-ioc-flags :unsigned-int)
                  "/usr/include/linux/perf_event.h:483:6"
                  (:ioc-flag-group 1))

(cffi:defbitfield (%linux.perf::event-read-format :unsigned-int)
                  "/usr/include/linux/perf_event.h:297:6"
                  (:total-time-enabled 1)
                  (:total-time-running 2)
                  (:id 4)
                  (:group 8)
                  (:max 16))

(cffi:defcenum (%linux.perf::event-sample-format :unsigned-long)
               "/usr/include/linux/perf_event.h:123:6"
               (:sample-ip 1)
               (:sample-tid 2)
               (:sample-time 4)
               (:sample-addr 8)
               (:sample-read 16)
               (:sample-callchain 32)
               (:sample-id 64)
               (:sample-cpu 128)
               (:sample-period 256)
               (:sample-stream-id 512)
               (:sample-raw 1024)
               (:sample-branch-stack 2048)
               (:sample-regs-user 4096)
               (:sample-stack-user 8192)
               (:sample-weight 16384)
               (:sample-data-src 32768)
               (:sample-identifier 65536)
               (:sample-transaction 131072)
               (:sample-regs-intr 262144)
               (:sample-phys-addr 524288)
               (:sample-aux 1048576)
               (:sample-cgroup 2097152)
               (:sample-data-page-size 4194304)
               (:sample-code-page-size 8388608)
               (:sample-weight-struct 16777216)
               (:sample-max 33554432)
               (:%%perf-sample-callchain-early -9223372036854775808))

(cffi:defcenum (%linux.perf::event-type :unsigned-int)
               "/usr/include/linux/perf_event.h:757:6"
               (:mmap 1)
               (:lost 2)
               (:comm 3)
               (:exit 4)
               (:throttle 5)
               (:unthrottle 6)
               (:fork 7)
               (:read 8)
               (:sample 9)
               (:mmap2 10)
               (:aux 11)
               (:itrace-start 12)
               (:lost-samples 13)
               (:switch 14)
               (:switch-cpu-wide 15)
               (:namespaces 16)
               (:ksymbol 17)
               (:bpf-event 18)
               (:cgroup 19)
               (:text-poke 20)
               (:max 21))

(cffi:defcenum (%linux.perf::hw-cache-id :unsigned-int)
               "/usr/include/linux/perf_event.h:70:6"
               (:l1d 0)
               (:l1i 1)
               (:ll 2)
               (:dtlb 3)
               (:itlb 4)
               (:bpu 5)
               (:node 6)
               (:max 7))

(cffi:defcenum (%linux.perf::hw-cache-op-id :unsigned-int)
               "/usr/include/linux/perf_event.h:82:6"
               (:read 0)
               (:write 1)
               (:prefetch 2)
               (:max 3))

(cffi:defcenum (%linux.perf::hw-cache-op-result-id :unsigned-int)
               "/usr/include/linux/perf_event.h:90:6"
               (:access 0)
               (:miss 1)
               (:max 2))

(cffi:defcenum (%linux.perf::hw-id :unsigned-int)
               "/usr/include/linux/perf_event.h:45:6"
               (:cpu-cycles 0)
               (:instructions 1)
               (:cache-references 2)
               (:cache-misses 3)
               (:branch-instructions 4)
               (:branch-misses 5)
               (:bus-cycles 6)
               (:stalled-cycles-frontend 7)
               (:stalled-cycles-backend 8)
               (:ref-cpu-cycles 9)
               (:max 10))

(cffi:defcenum (%linux.perf::record-ksymbol-type :unsigned-int)
               "/usr/include/linux/perf_event.h:1121:6"
               (:unknown 0)
               (:bpf 1)
               (:ool 2)
               (:max 3))

(cffi:defcenum (%linux.perf::sample-regs-abi :unsigned-int)
               "/usr/include/linux/perf_event.h:249:6"
               (:none 0)
               (:|32| 1)
               (:|64| 2))

(cffi:defcenum (%linux.perf::sw-ids :unsigned-int)
               "/usr/include/linux/perf_event.h:103:6"
               (:cpu-clock 0)
               (:task-clock 1)
               (:page-faults 2)
               (:context-switches 3)
               (:cpu-migrations 4)
               (:page-faults-min 5)
               (:page-faults-maj 6)
               (:alignment-faults 7)
               (:emulation-faults 8)
               (:dummy 9)
               (:bpf-output 10)
               (:max 11))

(cffi:defcenum (%linux.perf::type-id :unsigned-int)
               "/usr/include/linux/perf_event.h:29:6"
               (:hardware 0)
               (:software 1)
               (:tracepoint 2)
               (:hw-cache 3)
               (:raw 4)
               (:breakpoint 5)
               (:max 6))

(defparameter %linux.perf::+br-unknown+ 0)

(defparameter %linux.perf::+br-cond+ 1)

(defparameter %linux.perf::+br-uncond+ 2)

(defparameter %linux.perf::+br-ind+ 3)

(defparameter %linux.perf::+br-call+ 4)

(defparameter %linux.perf::+br-ind-call+ 5)

(defparameter %linux.perf::+br-ret+ 6)

(defparameter %linux.perf::+br-syscall+ 7)

(defparameter %linux.perf::+br-sysret+ 8)

(defparameter %linux.perf::+br-cond-call+ 9)

(defparameter %linux.perf::+br-cond-ret+ 10)

(defparameter %linux.perf::+br-max+ 11)

(defparameter %linux.perf::+txn-elision+ 1)

(defparameter %linux.perf::+txn-transaction+ 2)

(defparameter %linux.perf::+txn-sync+ 4)

(defparameter %linux.perf::+txn-async+ 8)

(defparameter %linux.perf::+txn-retry+ 16)

(defparameter %linux.perf::+txn-conflict+ 32)

(defparameter %linux.perf::+txn-capacity-write+ 64)

(defparameter %linux.perf::+txn-capacity-read+ 128)

(defparameter %linux.perf::+txn-max+ 256)

(defparameter %linux.perf::+txn-abort-mask+ -4294967296)

(defparameter %linux.perf::+txn-abort-shift+ 32)

(cffi:defctype %linux.perf::%%u64 :unsigned-long-long)

(cffi:defcstruct (%linux.perf::branch-entry :size 24)
                 (%linux.perf::from %linux.perf::%%u64 :offset 0)
                 (%linux.perf::to %linux.perf::%%u64 :offset 8)
                 (%linux.perf::mispred %linux.perf::%%u64 :offset 16)
                 (%linux.perf::predicted %linux.perf::%%u64 :offset
                  129/8)
                 (%linux.perf::in-tx %linux.perf::%%u64 :offset 65/4)
                 (%linux.perf::abort %linux.perf::%%u64 :offset
                  131/8)
                 (%linux.perf::cycles %linux.perf::%%u64 :offset
                  33/2)
                 (%linux.perf::type %linux.perf::%%u64 :offset 37/2)
                 (%linux.perf::reserved %linux.perf::%%u64 :offset
                  19))

(cffi:defcunion (%linux.perf::|C:@S@PERF-EVENT-ATTR@UA| :size 8)
                (%linux.perf::sample-period %linux.perf::%%u64)
                (%linux.perf::sample-freq %linux.perf::%%u64))

(cffi:defctype %linux.perf::%%s32 :int)

(cffi:defctype %linux.perf::%%u16 :unsigned-short)

(cffi:defctype %linux.perf::%%u32 :unsigned-int)

(cffi:defcstruct (%linux.perf::event-attr :size 120)
                 (%linux.perf::type %linux.perf::%%u32 :offset 0)
                 (%linux.perf::size %linux.perf::%%u32 :offset 4)
                 (%linux.perf::config %linux.perf::%%u64 :offset 8)
                 (%linux.perf::@0
                  (:union %linux.perf::|C:@S@PERF-EVENT-ATTR@UA|)
                  :offset 16)
                 (%linux.perf::sample-type %linux.perf::%%u64 :offset
                  24)
                 (%linux.perf::read-format %linux.perf::%%u64 :offset
                  32)
                 (%linux.perf::disabled %linux.perf::%%u64 :offset
                  40)
                 (%linux.perf::inherit %linux.perf::%%u64 :offset
                  321/8)
                 (%linux.perf::pinned %linux.perf::%%u64 :offset
                  161/4)
                 (%linux.perf::exclusive %linux.perf::%%u64 :offset
                  323/8)
                 (%linux.perf::exclude-user %linux.perf::%%u64
                  :offset 81/2)
                 (%linux.perf::exclude-kernel %linux.perf::%%u64
                  :offset 325/8)
                 (%linux.perf::exclude-hv %linux.perf::%%u64 :offset
                  163/4)
                 (%linux.perf::exclude-idle %linux.perf::%%u64
                  :offset 327/8)
                 (%linux.perf::mmap %linux.perf::%%u64 :offset 41)
                 (%linux.perf::comm %linux.perf::%%u64 :offset 329/8)
                 (%linux.perf::freq %linux.perf::%%u64 :offset 165/4)
                 (%linux.perf::inherit-stat %linux.perf::%%u64
                  :offset 331/8)
                 (%linux.perf::enable-on-exec %linux.perf::%%u64
                  :offset 83/2)
                 (%linux.perf::task %linux.perf::%%u64 :offset 333/8)
                 (%linux.perf::watermark %linux.perf::%%u64 :offset
                  167/4)
                 (%linux.perf::precise-ip %linux.perf::%%u64 :offset
                  335/8)
                 (%linux.perf::mmap-data %linux.perf::%%u64 :offset
                  337/8)
                 (%linux.perf::sample-id-all %linux.perf::%%u64
                  :offset 169/4)
                 (%linux.perf::exclude-host %linux.perf::%%u64
                  :offset 339/8)
                 (%linux.perf::exclude-guest %linux.perf::%%u64
                  :offset 85/2)
                 (%linux.perf::exclude-callchain-kernel
                  %linux.perf::%%u64 :offset 341/8)
                 (%linux.perf::exclude-callchain-user
                  %linux.perf::%%u64 :offset 171/4)
                 (%linux.perf::mmap2 %linux.perf::%%u64 :offset
                  343/8)
                 (%linux.perf::comm-exec %linux.perf::%%u64 :offset
                  43)
                 (%linux.perf::use-clockid %linux.perf::%%u64 :offset
                  345/8)
                 (%linux.perf::context-switch %linux.perf::%%u64
                  :offset 173/4)
                 (%linux.perf::write-backward %linux.perf::%%u64
                  :offset 347/8)
                 (%linux.perf::namespaces %linux.perf::%%u64 :offset
                  87/2)
                 (%linux.perf::ksymbol %linux.perf::%%u64 :offset
                  349/8)
                 (%linux.perf::bpf-event %linux.perf::%%u64 :offset
                  175/4)
                 (%linux.perf::aux-output %linux.perf::%%u64 :offset
                  351/8)
                 (%linux.perf::cgroup %linux.perf::%%u64 :offset 44)
                 (%linux.perf::text-poke %linux.perf::%%u64 :offset
                  353/8)
                 (%linux.perf::build-id %linux.perf::%%u64 :offset
                  177/4)
                 (%linux.perf::%%reserved-1 %linux.perf::%%u64
                  :offset 355/8)
                 (%linux.perf::@1
                  (:union %linux.perf::|C:@S@PERF-EVENT-ATTR@UA|)
                  :offset 48)
                 (%linux.perf::bp-type %linux.perf::%%u32 :offset 52)
                 (%linux.perf::@2
                  (:union %linux.perf::|C:@S@PERF-EVENT-ATTR@UA|)
                  :offset 56)
                 (%linux.perf::@3
                  (:union %linux.perf::|C:@S@PERF-EVENT-ATTR@UA|)
                  :offset 64)
                 (%linux.perf::branch-sample-type %linux.perf::%%u64
                  :offset 72)
                 (%linux.perf::sample-regs-user %linux.perf::%%u64
                  :offset 80)
                 (%linux.perf::sample-stack-user %linux.perf::%%u32
                  :offset 88)
                 (%linux.perf::clockid %linux.perf::%%s32 :offset 92)
                 (%linux.perf::sample-regs-intr %linux.perf::%%u64
                  :offset 96)
                 (%linux.perf::aux-watermark %linux.perf::%%u32
                  :offset 104)
                 (%linux.perf::sample-max-stack %linux.perf::%%u16
                  :offset 108)
                 (%linux.perf::%%reserved-2 %linux.perf::%%u16
                  :offset 110)
                 (%linux.perf::aux-sample-size %linux.perf::%%u32
                  :offset 112)
                 (%linux.perf::%%reserved-3 %linux.perf::%%u32
                  :offset 116))

(cffi:defcstruct (%linux.perf::event-header :size 8)
                 (%linux.perf::type %linux.perf::%%u32 :offset 0)
                 (%linux.perf::misc %linux.perf::%%u16 :offset 4)
                 (%linux.perf::size %linux.perf::%%u16 :offset 6))

(cffi:defctype %linux.perf::%%s64 :long-long)

(cffi:defcstruct (%linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA@SA|
                  :size 8)
                 (%linux.perf::cap-bit0 %linux.perf::%%u64 :offset 0)
                 (%linux.perf::cap-bit0-is-deprecated
                  %linux.perf::%%u64 :offset 1/8)
                 (%linux.perf::cap-user-rdpmc %linux.perf::%%u64
                  :offset 1/4)
                 (%linux.perf::cap-user-time %linux.perf::%%u64
                  :offset 3/8)
                 (%linux.perf::cap-user-time-zero %linux.perf::%%u64
                  :offset 1/2)
                 (%linux.perf::cap-user-time-short %linux.perf::%%u64
                  :offset 5/8)
                 (%linux.perf::cap-----res %linux.perf::%%u64 :offset
                  3/4))

(cffi:defcunion (%linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA| :size 8)
                (%linux.perf::capabilities %linux.perf::%%u64)
                (%linux.perf::@0
                 (:struct
                  %linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA@SA|)))

(cffi:defctype %linux.perf::%%u8 :unsigned-char)

(cffi:defcstruct (%linux.perf::event-mmap-page :size 1088)
                 (%linux.perf::version %linux.perf::%%u32 :offset 0)
                 (%linux.perf::compat-version %linux.perf::%%u32
                  :offset 4)
                 (%linux.perf::lock %linux.perf::%%u32 :offset 8)
                 (%linux.perf::index %linux.perf::%%u32 :offset 12)
                 (%linux.perf::offset %linux.perf::%%s64 :offset 16)
                 (%linux.perf::time-enabled %linux.perf::%%u64
                  :offset 24)
                 (%linux.perf::time-running %linux.perf::%%u64
                  :offset 32)
                 (%linux.perf::@0
                  (:union
                   %linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA|)
                  :offset 40)
                 (%linux.perf::pmc-width %linux.perf::%%u16 :offset
                  48)
                 (%linux.perf::time-shift %linux.perf::%%u16 :offset
                  50)
                 (%linux.perf::time-mult %linux.perf::%%u32 :offset
                  52)
                 (%linux.perf::time-offset %linux.perf::%%u64 :offset
                  56)
                 (%linux.perf::time-zero %linux.perf::%%u64 :offset
                  64)
                 (%linux.perf::size %linux.perf::%%u32 :offset 72)
                 (%linux.perf::%%reserved-1 %linux.perf::%%u32
                  :offset 76)
                 (%linux.perf::time-cycles %linux.perf::%%u64 :offset
                  80)
                 (%linux.perf::time-mask %linux.perf::%%u64 :offset
                  88)
                 (%linux.perf::%%reserved %linux.perf::%%u8 :count
                  928 :offset 96)
                 (%linux.perf::data-head %linux.perf::%%u64 :offset
                  1024)
                 (%linux.perf::data-tail %linux.perf::%%u64 :offset
                  1032)
                 (%linux.perf::data-offset %linux.perf::%%u64 :offset
                  1040)
                 (%linux.perf::data-size %linux.perf::%%u64 :offset
                  1048)
                 (%linux.perf::aux-head %linux.perf::%%u64 :offset
                  1056)
                 (%linux.perf::aux-tail %linux.perf::%%u64 :offset
                  1064)
                 (%linux.perf::aux-offset %linux.perf::%%u64 :offset
                  1072)
                 (%linux.perf::aux-size %linux.perf::%%u64 :offset
                  1080))

(cffi:defcstruct (%linux.perf::event-query-bpf :size 8)
                 (%linux.perf::ids-len %linux.perf::%%u32 :offset 0)
                 (%linux.perf::prog-cnt %linux.perf::%%u32 :offset 4)
                 (%linux.perf::ids %linux.perf::%%u32 :count 0
                  :offset 8))

(cffi:defcstruct (%linux.perf::ns-link-info :size 16)
                 (%linux.perf::dev %linux.perf::%%u64 :offset 0)
                 (%linux.perf::ino %linux.perf::%%u64 :offset 8))

(cffi:defcstruct (%linux.perf::|C:@U@PERF-MEM-DATA-SRC@SA| :size 8)
                 (%linux.perf::mem-op %linux.perf::%%u64 :offset 0)
                 (%linux.perf::mem-lvl %linux.perf::%%u64 :offset
                  5/8)
                 (%linux.perf::mem-snoop %linux.perf::%%u64 :offset
                  19/8)
                 (%linux.perf::mem-lock %linux.perf::%%u64 :offset 3)
                 (%linux.perf::mem-dtlb %linux.perf::%%u64 :offset
                  13/4)
                 (%linux.perf::mem-lvl-num %linux.perf::%%u64 :offset
                  33/8)
                 (%linux.perf::mem-remote %linux.perf::%%u64 :offset
                  37/8)
                 (%linux.perf::mem-snoopx %linux.perf::%%u64 :offset
                  19/4)
                 (%linux.perf::mem-blk %linux.perf::%%u64 :offset 5)
                 (%linux.perf::mem-rsvd %linux.perf::%%u64 :offset
                  43/8))

(cffi:defcunion (%linux.perf::mem-data-src :size 8)
                (%linux.perf::val %linux.perf::%%u64)
                (%linux.perf::@0
                 (:struct %linux.perf::|C:@U@PERF-MEM-DATA-SRC@SA|)))

(cffi:defcstruct (%linux.perf::|C:@U@PERF-SAMPLE-WEIGHT@SA| :size 8)
                 (%linux.perf::var1-dw %linux.perf::%%u32 :offset 0)
                 (%linux.perf::var2-w %linux.perf::%%u16 :offset 4)
                 (%linux.perf::var3-w %linux.perf::%%u16 :offset 6))

(cffi:defcunion (%linux.perf::sample-weight :size 8)
                (%linux.perf::full %linux.perf::%%u64)
                (%linux.perf::@0
                 (:struct %linux.perf::|C:@U@PERF-SAMPLE-WEIGHT@SA|)))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%linux.perf::lock :%linux.perf)
  (export '%linux.perf::+max-contexts-per-stack+ :%linux.perf)
  (export '%linux.perf::exclude-kernel :%linux.perf)
  (export '%linux.perf::type-id :%linux.perf)
  (export '%linux.perf::%%reserved-1 :%linux.perf)
  (export '%linux.perf::time-cycles :%linux.perf)
  (export '%linux.perf::time-running :%linux.perf)
  (export '%linux.perf::+record-misc-hypervisor+ :%linux.perf)
  (export '%linux.perf::var1-dw :%linux.perf)
  (export '%linux.perf::exclude-callchain-user :%linux.perf)
  (export '%linux.perf::+txn-async+ :%linux.perf)
  (export '%linux.perf::%%u64 :%linux.perf)
  (export '%linux.perf::watermark :%linux.perf)
  (export '%linux.perf::+record-misc-kernel+ :%linux.perf)
  (export '%linux.perf::+flag-pid-cgroup+ :%linux.perf)
  (export '%linux.perf::mem-dtlb :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-shift+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-hit+ :%linux.perf)
  (export '%linux.perf::in-tx :%linux.perf)
  (export '%linux.perf::+mem-snoop-shift+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-l3+ :%linux.perf)
  (export '%linux.perf::exclusive :%linux.perf)
  (export '%linux.perf::cap-----res :%linux.perf)
  (export '%linux.perf::+record-misc-switch-out-preempt+
          :%linux.perf)
  (export '%linux.perf::prog-cnt :%linux.perf)
  (export '%linux.perf::+br-ind+ :%linux.perf)
  (export '%linux.perf::sample-stack-user :%linux.perf)
  (export '%linux.perf::var2-w :%linux.perf)
  (export '%linux.perf::compat-version :%linux.perf)
  (export '%linux.perf::record-ksymbol-type :%linux.perf)
  (export '%linux.perf::+max-stack-depth+ :%linux.perf)
  (export '%linux.perf::+mem-lock-na+ :%linux.perf)
  (export '%linux.perf::comm :%linux.perf)
  (export '%linux.perf::+txn-max+ :%linux.perf)
  (export '%linux.perf::mem-lvl-num :%linux.perf)
  (export '%linux.perf::event-read-format :%linux.perf)
  (export '%linux.perf::offset :%linux.perf)
  (export '%linux.perf::time-offset :%linux.perf)
  (export '%linux.perf::bpf-event :%linux.perf)
  (export '%linux.perf::index :%linux.perf)
  (export '%linux.perf::+event-ioc-pause-output+ :%linux.perf)
  (export '%linux.perf::+mem-blk-shift+ :%linux.perf)
  (export '%linux.perf::clockid :%linux.perf)
  (export '%linux.perf::+record-ksymbol-flags-unregister+
          :%linux.perf)
  (export '%linux.perf::callchain-context :%linux.perf)
  (export '%linux.perf::use-clockid :%linux.perf)
  (export '%linux.perf::reserved :%linux.perf)
  (export '%linux.perf::mem-blk :%linux.perf)
  (export '%linux.perf::aux-output :%linux.perf)
  (export '%linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA@SA|
          :%linux.perf)
  (export '%linux.perf::aux-offset :%linux.perf)
  (export '%linux.perf::+event-ioc-reset+ :%linux.perf)
  (export '%linux.perf::cap-bit0-is-deprecated :%linux.perf)
  (export '%linux.perf::@2 :%linux.perf)
  (export '%linux.perf::misc :%linux.perf)
  (export '%linux.perf::ids-len :%linux.perf)
  (export '%linux.perf::+mem-lock-locked+ :%linux.perf)
  (export '%linux.perf::|C:@U@PERF-SAMPLE-WEIGHT@SA| :%linux.perf)
  (export '%linux.perf::sample-regs-abi :%linux.perf)
  (export '%linux.perf::time-mask :%linux.perf)
  (export '%linux.perf::sample-regs-user :%linux.perf)
  (export '%linux.perf::sample-weight :%linux.perf)
  (export '%linux.perf::%%s64 :%linux.perf)
  (export '%linux.perf::enable-on-exec :%linux.perf)
  (export '%linux.perf::task :%linux.perf)
  (export '%linux.perf::inherit :%linux.perf)
  (export '%linux.perf::+record-misc-user+ :%linux.perf)
  (export '%linux.perf::version :%linux.perf)
  (export '%linux.perf::+event-ioc-id+ :%linux.perf)
  (export '%linux.perf::dev :%linux.perf)
  (export '%linux.perf::+mem-snoopx-fwd+ :%linux.perf)
  (export '%linux.perf::type :%linux.perf)
  (export '%linux.perf::+record-misc-guest-kernel+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-l2+ :%linux.perf)
  (export '%linux.perf::+attr-size-ver2+ :%linux.perf)
  (export '%linux.perf::+br-cond-call+ :%linux.perf)
  (export '%linux.perf::+txn-capacity-read+ :%linux.perf)
  (export '%linux.perf::+mem-tlb-shift+ :%linux.perf)
  (export '%linux.perf::sample-period :%linux.perf)
  (export '%linux.perf::sample-max-stack :%linux.perf)
  (export '%linux.perf::+mem-lvl-rem-ram1+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-na+ :%linux.perf)
  (export '%linux.perf::+event-ioc-set-bpf+ :%linux.perf)
  (export '%linux.perf::+event-ioc-refresh+ :%linux.perf)
  (export '%linux.perf::+attr-size-ver4+ :%linux.perf)
  (export '%linux.perf::|C:@U@PERF-MEM-DATA-SRC@SA| :%linux.perf)
  (export '%linux.perf::capabilities :%linux.perf)
  (export '%linux.perf::cap-user-time-zero :%linux.perf)
  (export '%linux.perf::bpf-event-type :%linux.perf)
  (export '%linux.perf::event-attr :%linux.perf)
  (export '%linux.perf::exclude-idle :%linux.perf)
  (export '%linux.perf::+mem-snoop-na+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-pmem+ :%linux.perf)
  (export '%linux.perf::sample-freq :%linux.perf)
  (export '%linux.perf::+record-misc-ext-reserved+ :%linux.perf)
  (export '%linux.perf::+mem-blk-na+ :%linux.perf)
  (export '%linux.perf::+flag-fd-no-group+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-rem-cce1+ :%linux.perf)
  (export '%linux.perf::to :%linux.perf)
  (export '%linux.perf::%%reserved :%linux.perf)
  (export '%linux.perf::mem-rsvd :%linux.perf)
  (export '%linux.perf::comm-exec :%linux.perf)
  (export '%linux.perf::+aux-flag-overwrite+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-shift+ :%linux.perf)
  (export '%linux.perf::|C:@S@PERF-EVENT-MMAP-PAGE@UA| :%linux.perf)
  (export '%linux.perf::aux-head :%linux.perf)
  (export '%linux.perf::write-backward :%linux.perf)
  (export '%linux.perf::+record-misc-proc-map-parse-timeout+
          :%linux.perf)
  (export '%linux.perf::mmap :%linux.perf)
  (export '%linux.perf::cap-bit0 :%linux.perf)
  (export '%linux.perf::+br-syscall+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-ram+ :%linux.perf)
  (export '%linux.perf::+txn-abort-mask+ :%linux.perf)
  (export '%linux.perf::%%reserved-2 :%linux.perf)
  (export '%linux.perf::+attr-size-ver0+ :%linux.perf)
  (export '%linux.perf::exclude-guest :%linux.perf)
  (export '%linux.perf::+mem-snoopx-shift+ :%linux.perf)
  (export '%linux.perf::+mem-op-store+ :%linux.perf)
  (export '%linux.perf::cycles :%linux.perf)
  (export '%linux.perf::aux-size :%linux.perf)
  (export '%linux.perf::+mem-snoop-none+ :%linux.perf)
  (export '%linux.perf::mmap-data :%linux.perf)
  (export '%linux.perf::+mem-remote-shift+ :%linux.perf)
  (export '%linux.perf::+mem-tlb-wk+ :%linux.perf)
  (export '%linux.perf::data-head :%linux.perf)
  (export '%linux.perf::time-zero :%linux.perf)
  (export '%linux.perf::hw-cache-id :%linux.perf)
  (export '%linux.perf::data-size :%linux.perf)
  (export '%linux.perf::+txn-abort-shift+ :%linux.perf)
  (export '%linux.perf::exclude-hv :%linux.perf)
  (export '%linux.perf::+mem-tlb-na+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-rem-ram2+ :%linux.perf)
  (export '%linux.perf::build-id :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-lfb+ :%linux.perf)
  (export '%linux.perf::event-query-bpf :%linux.perf)
  (export '%linux.perf::+br-cond+ :%linux.perf)
  (export '%linux.perf::+txn-sync+ :%linux.perf)
  (export '%linux.perf::+mem-blk-addr+ :%linux.perf)
  (export '%linux.perf::+event-ioc-set-filter+ :%linux.perf)
  (export '%linux.perf::cgroup :%linux.perf)
  (export '%linux.perf::predicted :%linux.perf)
  (export '%linux.perf::event-type :%linux.perf)
  (export '%linux.perf::+mem-snoop-hit+ :%linux.perf)
  (export '%linux.perf::+br-ret+ :%linux.perf)
  (export '%linux.perf::+txn-transaction+ :%linux.perf)
  (export '%linux.perf::bp-type :%linux.perf)
  (export '%linux.perf::+mem-tlb-l2+ :%linux.perf)
  (export '%linux.perf::read-format :%linux.perf)
  (export '%linux.perf::+mem-tlb-l1+ :%linux.perf)
  (export '%linux.perf::+flag-fd-output+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-l2+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-lfb+ :%linux.perf)
  (export '%linux.perf::+mem-tlb-miss+ :%linux.perf)
  (export '%linux.perf::+record-misc-cpumode-unknown+ :%linux.perf)
  (export '%linux.perf::+mem-lock-shift+ :%linux.perf)
  (export '%linux.perf::+event-ioc-enable+ :%linux.perf)
  (export '%linux.perf::exclude-callchain-kernel :%linux.perf)
  (export '%linux.perf::aux-watermark :%linux.perf)
  (export '%linux.perf::text-poke :%linux.perf)
  (export '%linux.perf::%%u32 :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-na+ :%linux.perf)
  (export '%linux.perf::+record-misc-fork-exec+ :%linux.perf)
  (export '%linux.perf::+aux-flag-collision+ :%linux.perf)
  (export '%linux.perf::inherit-stat :%linux.perf)
  (export '%linux.perf::pmc-width :%linux.perf)
  (export '%linux.perf::+br-unknown+ :%linux.perf)
  (export '%linux.perf::mem-op :%linux.perf)
  (export '%linux.perf::+record-misc-comm-exec+ :%linux.perf)
  (export '%linux.perf::event-ioc-flags :%linux.perf)
  (export '%linux.perf::|C:@S@PERF-EVENT-ATTR@UA| :%linux.perf)
  (export '%linux.perf::+mem-tlb-hit+ :%linux.perf)
  (export '%linux.perf::disabled :%linux.perf)
  (export '%linux.perf::+flag-fd-cloexec+ :%linux.perf)
  (export '%linux.perf::config :%linux.perf)
  (export '%linux.perf::+event-ioc-query-bpf+ :%linux.perf)
  (export '%linux.perf::@3 :%linux.perf)
  (export '%linux.perf::+mem-op-exec+ :%linux.perf)
  (export '%linux.perf::+event-ioc-period+ :%linux.perf)
  (export '%linux.perf::exclude-user :%linux.perf)
  (export '%linux.perf::+mem-op-na+ :%linux.perf)
  (export '%linux.perf::+txn-elision+ :%linux.perf)
  (export '%linux.perf::cap-user-rdpmc :%linux.perf)
  (export '%linux.perf::+br-max+ :%linux.perf)
  (export '%linux.perf::+mem-op-load+ :%linux.perf)
  (export '%linux.perf::+attr-size-ver1+ :%linux.perf)
  (export '%linux.perf::ns-link-info :%linux.perf)
  (export '%linux.perf::hw-cache-op-result-id :%linux.perf)
  (export '%linux.perf::+record-misc-guest-user+ :%linux.perf)
  (export '%linux.perf::%%reserved-3 :%linux.perf)
  (export '%linux.perf::+br-sysret+ :%linux.perf)
  (export '%linux.perf::branch-sample-type :%linux.perf)
  (export '%linux.perf::+txn-retry+ :%linux.perf)
  (export '%linux.perf::+event-ioc-disable+ :%linux.perf)
  (export '%linux.perf::mmap2 :%linux.perf)
  (export '%linux.perf::mem-remote :%linux.perf)
  (export '%linux.perf::+mem-lvl-io+ :%linux.perf)
  (export '%linux.perf::+attr-size-ver6+ :%linux.perf)
  (export '%linux.perf::+event-ioc-set-output+ :%linux.perf)
  (export '%linux.perf::%%s32 :%linux.perf)
  (export '%linux.perf::sample-id-all :%linux.perf)
  (export '%linux.perf::sw-ids :%linux.perf)
  (export '%linux.perf::+br-ind-call+ :%linux.perf)
  (export '%linux.perf::from :%linux.perf)
  (export '%linux.perf::+aux-flag-partial+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-l4+ :%linux.perf)
  (export '%linux.perf::+record-misc-switch-out+ :%linux.perf)
  (export '%linux.perf::ids :%linux.perf)
  (export '%linux.perf::mem-lock :%linux.perf)
  (export '%linux.perf::+br-call+ :%linux.perf)
  (export '%linux.perf::data-tail :%linux.perf)
  (export '%linux.perf::+attr-size-ver5+ :%linux.perf)
  (export '%linux.perf::+record-misc-cpumode-mask+ :%linux.perf)
  (export '%linux.perf::full :%linux.perf)
  (export '%linux.perf::sample-regs-intr :%linux.perf)
  (export '%linux.perf::hw-cache-op-id :%linux.perf)
  (export '%linux.perf::namespaces :%linux.perf)
  (export '%linux.perf::+mem-op-pfetch+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-l1+ :%linux.perf)
  (export '%linux.perf::+record-misc-exact-ip+ :%linux.perf)
  (export '%linux.perf::mem-lvl :%linux.perf)
  (export '%linux.perf::branch-entry :%linux.perf)
  (export '%linux.perf::+mem-blk-data+ :%linux.perf)
  (export '%linux.perf::+mem-op-shift+ :%linux.perf)
  (export '%linux.perf::+attr-size-ver3+ :%linux.perf)
  (export '%linux.perf::+txn-conflict+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-unc+ :%linux.perf)
  (export '%linux.perf::+record-misc-mmap-data+ :%linux.perf)
  (export '%linux.perf::ino :%linux.perf)
  (export '%linux.perf::pinned :%linux.perf)
  (export '%linux.perf::%%u8 :%linux.perf)
  (export '%linux.perf::time-shift :%linux.perf)
  (export '%linux.perf::+mem-lvl-rem-cce2+ :%linux.perf)
  (export '%linux.perf::time-mult :%linux.perf)
  (export '%linux.perf::cap-user-time-short :%linux.perf)
  (export '%linux.perf::val :%linux.perf)
  (export '%linux.perf::branch-sample-type-shift :%linux.perf)
  (export '%linux.perf::+br-uncond+ :%linux.perf)
  (export '%linux.perf::+mem-snoop-miss+ :%linux.perf)
  (export '%linux.perf::time-enabled :%linux.perf)
  (export '%linux.perf::+br-cond-ret+ :%linux.perf)
  (export '%linux.perf::+txn-capacity-write+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-l3+ :%linux.perf)
  (export '%linux.perf::cap-user-time :%linux.perf)
  (export '%linux.perf::+record-misc-mmap-build-id+ :%linux.perf)
  (export '%linux.perf::+aux-flag-truncated+ :%linux.perf)
  (export '%linux.perf::var3-w :%linux.perf)
  (export '%linux.perf::aux-tail :%linux.perf)
  (export '%linux.perf::hw-id :%linux.perf)
  (export '%linux.perf::%%u16 :%linux.perf)
  (export '%linux.perf::@0 :%linux.perf)
  (export '%linux.perf::+mem-remote-remote+ :%linux.perf)
  (export '%linux.perf::+mem-tlb-os+ :%linux.perf)
  (export '%linux.perf::+mem-snoop-hitm+ :%linux.perf)
  (export '%linux.perf::+event-ioc-modify-attributes+ :%linux.perf)
  (export '%linux.perf::+sample-weight-type+ :%linux.perf)
  (export '%linux.perf::+mem-lvl-loc-ram+ :%linux.perf)
  (export '%linux.perf::size :%linux.perf)
  (export '%linux.perf::data-offset :%linux.perf)
  (export '%linux.perf::+mem-lvl-l1+ :%linux.perf)
  (export '%linux.perf::context-switch :%linux.perf)
  (export '%linux.perf::mem-snoop :%linux.perf)
  (export '%linux.perf::aux-sample-size :%linux.perf)
  (export '%linux.perf::sample-type :%linux.perf)
  (export '%linux.perf::@1 :%linux.perf)
  (export '%linux.perf::event-sample-format :%linux.perf)
  (export '%linux.perf::ksymbol :%linux.perf)
  (export '%linux.perf::mispred :%linux.perf)
  (export '%linux.perf::event-header :%linux.perf)
  (export '%linux.perf::mem-data-src :%linux.perf)
  (export '%linux.perf::mem-snoopx :%linux.perf)
  (export '%linux.perf::+mem-lvl-miss+ :%linux.perf)
  (export '%linux.perf::abort :%linux.perf)
  (export '%linux.perf::event-mmap-page :%linux.perf)
  (export '%linux.perf::exclude-host :%linux.perf)
  (export '%linux.perf::+sample-branch-plm-all+ :%linux.perf)
  (export '%linux.perf::+mem-lvlnum-any-cache+ :%linux.perf)
  (export '%linux.perf::freq :%linux.perf)
  (export '%linux.perf::precise-ip :%linux.perf)
  (setf (getf (symbol-plist '%linux.perf::@0)
              :cffi-c-ref-anonymous-field)
        t
        (getf (symbol-plist '%linux.perf::@3)
              :cffi-c-ref-anonymous-field)
        t
        (getf (symbol-plist '%linux.perf::@2)
              :cffi-c-ref-anonymous-field)
        t
        (getf (symbol-plist '%linux.perf::@1)
              :cffi-c-ref-anonymous-field)
        t))

